name: 🐹GO CI
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ (github.event.pull_request && github.event.pull_request.number) || github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: []
    name: ${{matrix.folder}}
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Install Rust
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: 1.22.x
  
      - name: Install Test Tools
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2
        working-directory: ${{matrix.folder}}

      - name: Lint
        run: golangci-lint -v run
        working-directory: ${{matrix.folder}}

      - name: Run tests
        run: go test ./...
        working-directory: ${{matrix.folder}}
